// src/components/lite/LiteHeader.vue
<template>
  <header class="lite-header">
    <div class="lite-header__inner">
      <!-- Left: Avatar + Greeting -->
      <div class="lite-header__left">
        <button
          class="lite-header__avatar"
          @click="$emit('avatar-click')"
          aria-label="Abrir menú de perfil"
        >
          <img v-if="user?.avatar" :src="user.avatar" :alt="user?.name || 'U'" />
          <span v-else class="lite-header__initial">{{ initials }}</span>
        </button>
        <div class="lite-header__greeting">
          <span class="lite-header__greeting-label">{{ greeting }}</span>
          <span class="lite-header__greeting-name">{{ user?.name || 'Usuario' }}</span>
        </div>
      </div>

      <!-- Right: Currency + Visibility + Theme + Notifications + Menu -->
      <div class="lite-header__right">
        <div class="lite-header__currency">{{ currency }}</div>
        <span class="lite-header__divider" />

        <button
          class="lite-header__icon-btn"
          :aria-label="hideValues ? 'Mostrar saldos' : 'Ocultar saldos'"
          @click="toggleHideValues"
        >
          <q-icon :name="hideValues ? 'visibility_off' : 'visibility'" size="20px" />
        </button>

        <button
          class="lite-header__icon-btn"
          :aria-label="isDark ? 'Modo claro' : 'Modo oscuro'"
          @click="toggleDark"
        >
          <q-icon :name="isDark ? 'light_mode' : 'dark_mode'" size="20px" />
        </button>

        <div class="lite-header__notif-wrap">
          <button
            class="lite-header__icon-btn"
            aria-label="Notificaciones"
            @click="$emit('notifications-click')"
          >
            <q-icon name="notifications" size="20px" />
          </button>
          <span v-if="(notificationCount ?? 0) > 0" class="lite-header__notif-dot" />
        </div>

        <button
          class="lite-header__icon-btn"
          aria-label="Abrir menú"
          @click="$emit('menu-click')"
        >
          <q-icon name="menu" size="20px" />
        </button>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useQuasar } from 'quasar';
import { useUiStore } from 'stores/ui';

interface User {
  name?: string;
  avatar?: string | null;
}

const props = defineProps<{
  user?: User;
  currency?: string;
  notificationCount?: number;
}>();

defineEmits<{
  'avatar-click': [];
  'notifications-click': [];
  'menu-click': [];
}>();

const $q = useQuasar();
const ui = useUiStore();

const initials = computed(() => {
  const name = props.user?.name || '';
  return name
    .split(' ')
    .map((n) => n[0])
    .join('')
    .toUpperCase()
    .slice(0, 2);
});

const greeting = computed(() => {
  const hour = new Date().getHours();
  if (hour < 12) return 'Buenos días,';
  if (hour < 19) return 'Buenas tardes,';
  return 'Buenas noches,';
});

const hideValues = computed(() => ui.hideValues);
const isDark = computed(() => $q.dark.isActive);

function toggleHideValues() {
  ui.toggleHideValues();
}

function toggleDark() {
  $q.dark.toggle();
  // Persistir preferencia
  try {
    localStorage.setItem('ow-theme', $q.dark.isActive ? 'dark' : 'light');
  } catch {
    // ignore
  }
}
</script>

<style scoped lang="scss">
.lite-header {
  padding: 18px 32px 14px;
  max-width: var(--container-max);
  margin: 0 auto;
  width: 100%;
  box-sizing: border-box;

  &__inner {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 16px;
  }

  &__left {
    display: flex;
    align-items: center;
    gap: 13px;
  }

  &__avatar {
    width: 42px;
    height: 42px;
    border: 0;
    padding: 0;
    cursor: pointer;
    border-radius: var(--radius-pill);
    background: var(--brand-primary);
    color: var(--fg-on-brand);
    font-family: var(--font-display);
    font-weight: 600;
    font-size: 16px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    overflow: hidden;

    img {
      width: 100%;
      height: 100%;
      object-fit: cover;
    }
  }

  &__initial {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 100%;
    height: 100%;
  }

  &__greeting {
    display: flex;
    flex-direction: column;
    gap: 1px;
    line-height: 1.25;

    &-label {
      font-family: var(--font-body);
      font-size: 12.5px;
      font-weight: 500;
      color: var(--fg-2);
      white-space: nowrap;
    }

    &-name {
      font-family: var(--font-display);
      font-weight: 600;
      font-size: 17px;
      color: var(--fg-1);
      white-space: nowrap;
      letter-spacing: -0.01em;
    }
  }

  &__right {
    display: flex;
    align-items: center;
    gap: 8px;
  }

  &__currency {
    font-family: var(--font-body);
    font-size: 13px;
    font-weight: 600;
    color: var(--fg-2);
    padding: 4px 10px;
    border-radius: var(--radius-pill);
    background: var(--surface-2);
  }

  &__divider {
    width: 1px;
    height: 22px;
    background: var(--border-hairline);
    margin: 0 2px;
    flex-shrink: 0;
  }

  &__icon-btn {
    width: 36px;
    height: 36px;
    border: none;
    background: transparent;
    border-radius: 10px;
    color: var(--fg-2);
    display: inline-flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    transition: all 160ms ease;

    &:hover {
      background: var(--surface-2);
      color: var(--fg-1);
    }

    &:active {
      transform: scale(0.96);
    }
  }

  &__notif-wrap {
    position: relative;
  }

  &__notif-dot {
    position: absolute;
    top: 4px;
    right: 4px;
    width: 8px;
    height: 8px;
    border-radius: 999px;
    background: var(--expense);
    box-shadow: 0 0 0 2px var(--surface-1);
  }
}

@media (max-width: 640px) {
  .lite-header {
    padding: 14px 16px 10px;

    &__greeting-name {
      font-size: 15px;
    }
  }
}
</style>

// rediseno/rediseno/ui_kits/lite-desktop/organisms/LiteHeader.jsx
/* global React */
const { useState: useHdr } = React;

function LiteHeader({ user, currency, balanceVisible, onToggleVisibility, onOpenMenu, onOpenNotifications, onAvatarClick, notificationCount = 2 }) {
  const theme = useAppTheme();
  return (
    <header style={{
      display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      gap: 16, padding: '18px 32px 14px',
      maxWidth: 'var(--container-max)', margin: '0 auto', width: '100%',
      boxSizing: 'border-box',
    }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 13 }}>
        <button
          onClick={onAvatarClick}
          aria-label="Open profile menu"
          style={{
            width: 42, height: 42, border: 0, padding: 0, cursor: 'pointer',
            borderRadius: 'var(--radius-pill)',
            background: 'var(--brand-primary)',
            color: 'var(--fg-on-brand)',
            fontFamily: 'var(--font-display)', fontWeight: 600, fontSize: 16,
            display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
            flexShrink: 0,
          }}
        >{user.initial}</button>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 1, lineHeight: 1.25 }}>
          <span style={{ fontFamily: 'var(--font-body)', fontSize: 12.5, fontWeight: 500, color: 'var(--fg-2)', whiteSpace: 'nowrap' }}>{t(user.greeting)}</span>
          <span style={{ fontFamily: 'var(--font-display)', fontWeight: 600, fontSize: 17, color: 'var(--fg-1)', whiteSpace: 'nowrap', letterSpacing: '-0.01em' }}>{user.name}</span>
        </div>
      </div>

      <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
        <CurrencyChip code={currency} />
        <span style={{ width: 1, height: 22, background: 'var(--border-hairline)', margin: '0 2px', flexShrink: 0 }} />
        <IconButton
          icon={balanceVisible ? 'visibility' : 'visibility_off'}
          ariaLabel={balanceVisible ? 'Hide balance' : 'Show balance'}
          onClick={onToggleVisibility}
        />
        <IconButton
          icon={theme === 'dark' ? 'light_mode' : 'dark_mode'}
          ariaLabel={theme === 'dark' ? 'Modo claro' : 'Modo oscuro'}
          onClick={() => window.toggleAppTheme && window.toggleAppTheme()}
        />
        <div style={{ position: 'relative' }}>
          <IconButton icon="notifications" ariaLabel="Notifications" onClick={onOpenNotifications} />
          {notificationCount > 0 && (
            <span style={{
              position: 'absolute', top: 6, right: 6,
              width: 8, height: 8, borderRadius: 999,
              background: 'var(--expense)',
              boxShadow: '0 0 0 2px var(--surface-1)',
            }} />
          )}
        </div>
        <IconButton icon="menu" ariaLabel="Open menu" onClick={onOpenMenu} />
      </div>
    </header>
  );
}

Object.assign(window, { LiteHeader });
