// src/components/liquid/DesktopQuickModal.vue
<template>
  <transition name="dqm-fade">
    <div v-if="modelValue" class="dqm-scrim" @click="onClose">
      <div class="dqm-card" role="dialog" aria-label="Agregar movimiento" @click.stop>
        <!-- Header -->
        <div class="dqm-header">
          <div>
            <div class="dqm-eyebrow">Acción rápida</div>
            <div class="dqm-title">¿Qué quieres registrar?</div>
          </div>
          <button class="dqm-close" aria-label="Cerrar" @click="onClose">
            <q-icon name="close" size="20px" />
          </button>
        </div>

        <!-- Step 1: Tipo -->
        <div class="dqm-section">
          <div class="dqm-section__head">
            <span class="dqm-label">Tipo de movimiento</span>
            <span class="dqm-step">Paso 1 de 2</span>
          </div>
          <div class="dqm-segmented">
            <button
              v-for="t in TYPES"
              :key="t.id"
              class="dqm-segmented__btn"
              :class="{ 'dqm-segmented__btn--active': type === t.id }"
              :style="type === t.id ? { color: t.color } : {}"
              @click="type = t.id"
            >
              <q-icon :name="t.icon" size="16px" />
              {{ t.label }}
            </button>
          </div>
        </div>

        <!-- Step 2: Método -->
        <div class="dqm-section">
          <div class="dqm-section__head">
            <span class="dqm-label">¿Cómo lo querés ingresar?</span>
            <span class="dqm-step">Paso 2 de 2</span>
          </div>
          <div class="dqm-methods">
            <button
              v-for="m in METHODS"
              :key="m.id"
              class="dqm-method"
              :style="{ '--dqm-accent': m.accent, '--dqm-tint': m.tint }"
              @click="choose(m.id)"
            >
              <div class="dqm-method__top">
                <div class="dqm-method__icon">
                  <q-icon :name="m.icon" size="20px" />
                </div>
                <div class="dqm-method__label-row">
                  <span class="dqm-method__label">{{ m.label }}</span>
                  <span v-if="m.badge" class="dqm-badge">{{ m.badge }}</span>
                </div>
              </div>
              <span class="dqm-method__sub">{{ m.sub }}</span>
              <div v-if="m.chips" class="dqm-chips">
                <span v-for="c in m.chips" :key="c" class="dqm-chip">{{ c }}</span>
              </div>
            </button>
          </div>
        </div>

        <div class="dqm-sep" />

        <!-- Movimientos especiales -->
        <div class="dqm-section">
          <div class="dqm-section__head">
            <span class="dqm-label">O registrá un movimiento especial</span>
          </div>
          <div class="dqm-plans">
            <button
              v-for="p in PLANS"
              :key="p.id"
              class="dqm-plan"
              :style="{ '--dqm-accent': p.accent, '--dqm-tint': p.tint }"
              @click="choosePlan(p.id)"
            >
              <div class="dqm-plan__head">
                <div class="dqm-plan__icon">
                  <q-icon :name="p.icon" size="16px" />
                </div>
                <span class="dqm-plan__label">{{ p.label }}</span>
                <span v-if="p.badge" class="dqm-badge dqm-badge--plan">{{ p.badge }}</span>
              </div>
              <span class="dqm-plan__sub">{{ p.sub }}</span>
            </button>
          </div>
        </div>

        <div class="dqm-sep" />

        <!-- CTA Asesor IA -->
        <button class="dqm-ai-btn" @click="openAI">
          <q-icon name="psychology" size="20px" />
          ¿Tenés una duda? Hablá con el Asesor IA
        </button>
      </div>
    </div>
  </transition>
</template>

<script setup lang="ts">
import { ref, watch, onBeforeUnmount } from 'vue';
import { useRouter } from 'vue-router';
import { useUiStore } from 'stores/ui';

type TypeId = 'expense' | 'income' | 'transfer';
type MethodId = 'text' | 'voice' | 'photo' | 'autoai';
type PlanId = 'debt' | 'dream' | 'jar';

interface Props {
  modelValue?: boolean;
}

const props = withDefaults(defineProps<Props>(), { modelValue: false });
const emit = defineEmits<{
  'update:modelValue': [visible: boolean];
}>();

const router = useRouter();
const ui = useUiStore();

const type = ref<TypeId>('expense');

const TYPES: { id: TypeId; label: string; icon: string; color: string }[] = [
  { id: 'expense', label: 'Gasto', icon: 'arrow_outward', color: 'var(--expense)' },
  { id: 'income', label: 'Ingreso', icon: 'arrow_downward', color: 'var(--income)' },
  { id: 'transfer', label: 'Transferir', icon: 'swap_horiz', color: '#8B5CF6' },
];

const METHODS: { id: MethodId; label: string; sub: string; icon: string; accent: string; tint: string; badge?: string; chips?: string[] }[] = [
  { id: 'text', label: 'Escribir', sub: 'Completá monto, comercio y categoría paso a paso.', icon: 'edit_note', accent: 'var(--brand-primary)', tint: 'var(--brand-primary-soft)' },
  { id: 'voice', label: 'Nota de voz', sub: 'Dictá la transacción — la IA la transcribe y categoriza.', icon: 'mic', accent: '#0EA5E9', tint: 'rgba(14,165,233,0.10)', badge: 'Transcripción IA' },
  { id: 'photo', label: 'Foto de factura', sub: 'Sacá la foto y se extraen todos los datos del recibo.', icon: 'receipt_long', accent: '#F59E0B', tint: 'rgba(245,158,11,0.10)', chips: ['Monto', 'Comercio', 'Items', 'Fecha', 'IVA'] },
  { id: 'autoai', label: 'Auto IA', sub: 'Pegá un mensaje o describí en lenguaje natural.', icon: 'auto_awesome', accent: '#8B5CF6', tint: 'rgba(139,92,246,0.10)', badge: 'Beta' },
];

const PLANS: { id: PlanId; label: string; sub: string; icon: string; accent: string; tint: string; badge?: string; route: string }[] = [
  { id: 'debt', label: 'Pago de deuda', sub: 'Cuota Cashea, tarjeta, préstamo o personal.', icon: 'credit_card', accent: '#EF4444', tint: 'rgba(239,68,68,0.10)', badge: 'Cashea', route: '/user/debts' },
  { id: 'dream', label: 'Aporte a sueño', sub: 'Sumá al ahorro de una meta de largo plazo.', icon: 'auto_awesome', accent: '#8B5CF6', tint: 'rgba(139,92,246,0.10)', route: '/user/dreams' },
  { id: 'jar', label: 'Aporte a jar', sub: 'Movimiento hacia un jar de corto plazo.', icon: 'savings', accent: 'var(--brand-primary)', tint: 'var(--brand-primary-soft)', route: '/user/jars' },
];

const METHOD_TO_TAB: Record<MethodId, 'write' | 'voice' | 'photo' | 'autoai'> = {
  text: 'write',
  voice: 'voice',
  photo: 'photo',
  autoai: 'autoai',
};

function onClose() {
  emit('update:modelValue', false);
}

function choose(methodId: MethodId) {
  ui.openSmartModal(METHOD_TO_TAB[methodId], type.value);
  onClose();
}

async function choosePlan(planId: PlanId) {
  const plan = PLANS.find((p) => p.id === planId);
  onClose();
  if (plan) await router.push(plan.route);
}

async function openAI() {
  onClose();
  await router.push('/user/asesor');
}

function onKeydown(e: KeyboardEvent) {
  if (e.key === 'Escape') onClose();
}

watch(
  () => props.modelValue,
  (open) => {
    if (open) {
      type.value = 'expense';
      document.addEventListener('keydown', onKeydown);
    } else {
      document.removeEventListener('keydown', onKeydown);
    }
  },
);

onBeforeUnmount(() => document.removeEventListener('keydown', onKeydown));
</script>

<style lang="scss" scoped>
.dqm-scrim {
  position: fixed;
  inset: 0;
  z-index: var(--z-modal);
  background: rgba(10, 14, 28, 0.55);
  backdrop-filter: blur(4px);
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 16px;
  box-sizing: border-box;
}

.dqm-card {
  width: min(620px, 100%);
  max-height: 92vh;
  overflow-y: auto;
  background: var(--surface-1);
  border-radius: var(--radius-xl);
  padding: 28px;
  box-shadow: var(--shadow-popover);
}

.dqm-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  margin-bottom: 22px;
}

.dqm-eyebrow {
  font-family: var(--font-body);
  font-size: 11px;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--fg-3);
}

.dqm-title {
  font-family: var(--font-display);
  font-size: 22px;
  font-weight: 700;
  color: var(--fg-1);
  margin-top: 4px;
}

.dqm-close {
  border: none;
  background: var(--surface-2);
  color: var(--fg-2);
  width: 34px;
  height: 34px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  flex-shrink: 0;
}

.dqm-section {
  margin-bottom: 22px;
}

.dqm-section__head {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  margin-bottom: 10px;
}

.dqm-label {
  font-family: var(--font-body);
  font-size: 11px;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--fg-3);
}

.dqm-step {
  font-family: var(--font-body);
  font-size: 12px;
  color: var(--fg-2);
}

.dqm-segmented {
  display: flex;
  gap: 4px;
  background: var(--surface-2);
  border-radius: var(--radius-pill);
  padding: 4px;
}

.dqm-segmented__btn {
  flex: 1;
  border: 0;
  cursor: pointer;
  padding: 10px 12px;
  border-radius: var(--radius-pill);
  background: transparent;
  color: var(--fg-2);
  font-family: var(--font-body);
  font-size: 13px;
  font-weight: 500;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  transition: all 160ms ease-out;

  &--active {
    background: var(--surface-1);
    font-weight: 700;
    box-shadow: var(--shadow-card);
  }
}

.dqm-methods {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 10px;
}

.dqm-method {
  text-align: left;
  border: 1px solid var(--border-hairline);
  cursor: pointer;
  background: var(--surface-1);
  border-radius: var(--radius-lg);
  padding: 14px 14px 16px;
  display: flex;
  flex-direction: column;
  gap: 8px;
  min-height: 116px;
  transition: all 160ms ease-out;

  &:hover {
    border-color: var(--dqm-accent);
    background: var(--dqm-tint);
  }

  &__top {
    display: flex;
    align-items: center;
    gap: 10px;
  }

  &__icon {
    width: 36px;
    height: 36px;
    border-radius: var(--radius-md);
    background: var(--dqm-tint);
    color: var(--dqm-accent);
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
  }

  &__label-row {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 8px;
    min-width: 0;
  }

  &__label {
    font-family: var(--font-display);
    font-weight: 700;
    font-size: 15px;
    color: var(--fg-1);
  }

  &__sub {
    font-family: var(--font-body);
    font-size: 12.5px;
    color: var(--fg-2);
    line-height: 1.45;
  }
}

.dqm-badge {
  font-family: var(--font-body);
  font-size: 10px;
  font-weight: 700;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  padding: 3px 7px;
  border-radius: var(--radius-pill);
  background: var(--dqm-tint);
  color: var(--dqm-accent);
  white-space: nowrap;

  &--plan {
    margin-left: auto;
    font-size: 9px;
  }
}

.dqm-chips {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
  margin-top: auto;
  padding-top: 4px;
}

.dqm-chip {
  font-family: var(--font-body);
  font-size: 10.5px;
  font-weight: 600;
  padding: 3px 7px;
  border-radius: var(--radius-pill);
  background: var(--surface-2);
  color: var(--fg-2);
  border: 1px solid var(--border-hairline);
}

.dqm-sep {
  height: 1px;
  background: var(--border-hairline);
  margin: 0 0 18px;
}

.dqm-plans {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 10px;
}

.dqm-plan {
  text-align: left;
  cursor: pointer;
  border: 1px solid var(--border-hairline);
  background: var(--surface-1);
  border-radius: var(--radius-lg);
  padding: 12px 12px 14px;
  display: flex;
  flex-direction: column;
  gap: 6px;
  transition: all 160ms ease-out;

  &:hover {
    border-color: var(--dqm-accent);
    background: var(--dqm-tint);
  }

  &__head {
    display: flex;
    align-items: center;
    gap: 8px;
  }

  &__icon {
    width: 28px;
    height: 28px;
    border-radius: var(--radius-sm);
    background: var(--dqm-tint);
    color: var(--dqm-accent);
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
  }

  &__label {
    font-family: var(--font-display);
    font-weight: 700;
    font-size: 13px;
    color: var(--fg-1);
  }

  &__sub {
    font-family: var(--font-body);
    font-size: 11.5px;
    color: var(--fg-2);
    line-height: 1.4;
  }
}

.dqm-ai-btn {
  width: 100%;
  border: 0;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
  padding: 14px;
  border-radius: var(--radius-pill);
  background: linear-gradient(90deg, #7c3aed 0%, #2563eb 60%, #0ea5e9 100%);
  color: #fff;
  font-family: var(--font-display);
  font-weight: 700;
  font-size: 15px;
  box-shadow: 0 6px 24px rgba(124, 58, 237, 0.3);
  transition: opacity 160ms;

  &:hover {
    opacity: 0.88;
  }
}

.dqm-fade-enter-active,
.dqm-fade-leave-active {
  transition: opacity 200ms ease-out;
}
.dqm-fade-enter-from,
.dqm-fade-leave-to {
  opacity: 0;
}

@media (max-width: 599px) {
  .dqm-plans {
    grid-template-columns: 1fr;
  }
}
</style>

// rediseno/ui_kits/lite-desktop/organisms/DesktopQuickModal.jsx
/* ─── Desktop Quick Action Modal ────────────────────────────────────────
 * Lite + Pro modal for adding a movement.
 *
 *   Step 1 — pick type   (Gasto / Ingreso / Transferir) — segmented
 *   Step 2 — pick method (Escribir / Voz / Foto / Auto IA) — tiles
 *
 * Emits onSelectAction("<type>:<method>"), e.g. "expense:voice".
 * The shell parses and forwards to SmartTransactionModal.
 *
 * Props: open, onClose, onOpenAI, onSelectAction, mode('lite'|'pro')
 * ──────────────────────────────────────────────────────────────────────── */
/* global React */

const DQM_TYPES = [
  { id: 'expense',  label: 'Gasto',      icon: 'arrow_outward',  color: 'var(--expense)' },
  { id: 'income',   label: 'Ingreso',    icon: 'arrow_downward', color: 'var(--income)'  },
  { id: 'transfer', label: 'Transferir', icon: 'swap_horiz',     color: '#8B5CF6'        },
];

const DQM_PLANS = [
  {
    id: 'debt',
    label: 'Pago de deuda',
    sub: 'Cuota Cashea, tarjeta, préstamo o personal.',
    icon: 'credit_card',
    accent: '#EF4444',
    tint: 'rgba(239,68,68,0.10)',
    badge: 'Cashea',
  },
  {
    id: 'dream',
    label: 'Aporte a sueño',
    sub: 'Sumá al ahorro de una meta de largo plazo.',
    icon: 'auto_awesome',
    accent: '#8B5CF6',
    tint: 'rgba(139,92,246,0.10)',
  },
  {
    id: 'jar',
    label: 'Aporte a jar',
    sub: 'Movimiento hacia un jar de corto plazo.',
    icon: 'savings',
    accent: 'var(--brand-primary)',
    tint: 'var(--brand-primary-soft)',
  },
];

const DQM_METHODS = [
  {
    id: 'text',
    label: 'Escribir',
    sub:  'Completá monto, comercio y categoría paso a paso.',
    icon: 'edit_note',
    accent: 'var(--brand-primary)',
    tint:   'var(--brand-primary-soft)',
  },
  {
    id: 'voice',
    label: 'Nota de voz',
    sub:  'Dictá la transacción — la IA la transcribe y categoriza.',
    icon: 'mic',
    accent: '#0EA5E9',
    tint:   'rgba(14,165,233,0.10)',
    badge:  'Transcripción IA',
  },
  {
    id: 'photo',
    label: 'Foto de factura',
    sub:  'Sacá la foto y se extraen todos los datos del recibo.',
    icon: 'receipt_long',
    accent: '#F59E0B',
    tint:   'rgba(245,158,11,0.10)',
    chips:  ['Monto', 'Comercio', 'Items', 'Fecha', 'IVA'],
  },
  {
    id: 'autoai',
    label: 'Auto IA',
    sub:  'Pegá un mensaje o describí en lenguaje natural.',
    icon: 'auto_awesome',
    accent: '#8B5CF6',
    tint:   'rgba(139,92,246,0.10)',
    badge:  'Beta',
  },
];

function DesktopQuickModal({ open, onClose, onOpenAI, onSelectAction, mode = 'lite' }) {
  const [type, setType] = React.useState('expense');
  const isMobile = useViewportMobile();

  React.useEffect(() => {
    if (!open) return;
    setType('expense'); // reset on each open
    const onKey = (e) => { if (e.key === 'Escape') onClose(); };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open, onClose]);

  if (!open) return null;

  const choose = (methodId) => {
    onClose();
    const mapped = methodId === 'autoai' ? 'text' : methodId;
    onSelectAction && onSelectAction(`${type}:${mapped}`);
  };

  const choosePlan = (planId) => {
    onClose();
    onSelectAction && onSelectAction(`${planId}:text`);
  };

  const activeType = DQM_TYPES.find(t => t.id === type);

  return (
    <div
      onClick={onClose}
      style={{
        position: isMobile ? 'absolute' : 'fixed', inset: 0, zIndex: 'var(--z-modal)',
        background: 'rgba(10,14,28,0.55)',
        backdropFilter: 'blur(4px)',
        display: 'flex',
        alignItems: isMobile ? 'flex-end' : 'center',
        justifyContent: 'center',
        padding: isMobile ? 0 : 16, boxSizing: 'border-box',
        animation: 'dqmFade 200ms var(--ease-out)',
      }}
    >
      <style>{`
        @keyframes dqmFade { from{opacity:0} to{opacity:1} }
        @keyframes dqmRise { from{opacity:0;transform:scale(0.97) translateY(8px)} to{opacity:1;transform:scale(1) translateY(0)} }
        @keyframes dqmSheet { from{transform:translateY(100%)} to{transform:translateY(0)} }
      `}</style>

      <div
        role="dialog" aria-label="Agregar movimiento"
        onClick={e => e.stopPropagation()}
        style={isMobile ? {
          position: 'absolute', left: 0, right: 0, bottom: 0,
          width: '100%', maxWidth: 'none', boxSizing: 'border-box',
          maxHeight: '90%', overflow: 'auto',
          background: 'var(--surface-1)',
          borderRadius: '22px 22px 0 0',
          padding: '10px 18px calc(20px + env(safe-area-inset-bottom))',
          boxShadow: '0 -10px 40px rgba(0,0,0,0.28)',
          animation: 'dqmFade 200ms var(--ease-out)',
        } : {
          width: 'min(620px, 100%)',
          maxHeight: '92vh', overflow: 'auto',
          background: 'var(--surface-1)',
          borderRadius: 'var(--radius-xl)',
          padding: '28px',
          boxShadow: 'var(--shadow-popover)',
          animation: 'dqmRise 240ms var(--ease-out)',
        }}
      >
        {/* Grab handle (mobile sheet) */}
        {isMobile && (
          <div style={{ width: 38, height: 4, borderRadius: 999, background: 'var(--border-strong, var(--border-hairline))', margin: '0 auto 14px', flexShrink: 0 }} />
        )}
        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 22 }}>
          <div>
            <div className="t-eyebrow">{t('Acción rápida')}</div>
            <div className="t-h2" style={{ marginTop: 4 }}>{t('¿Qué quieres registrar?')}</div>
          </div>
          <IconButton icon="close" ariaLabel="Cerrar" onClick={onClose} />
        </div>

        {/* ── Step 1 · Type ───────────────────────────────────── */}
        <div style={{ marginBottom: 22 }}>
          <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', marginBottom: 10 }}>
            <span style={{ fontFamily: 'var(--font-body)', fontSize: 11, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', color: 'var(--fg-3)' }}>
              {t('Tipo de movimiento')}
            </span>
            <span style={{ fontFamily: 'var(--font-body)', fontSize: 12, color: 'var(--fg-2)' }}>
              {t('Paso 1 de 2')}
            </span>
          </div>

          <div style={{
            display: 'flex', gap: 4,
            background: 'var(--surface-2)',
            borderRadius: 'var(--radius-pill)',
            padding: 4,
          }}>
            {DQM_TYPES.map(t => {
              const active = type === t.id;
              return (
                <button
                  key={t.id}
                  onClick={() => setType(t.id)}
                  style={{
                    flex: 1, border: 0, cursor: 'pointer',
                    padding: '10px 12px',
                    borderRadius: 'var(--radius-pill)',
                    background: active ? 'var(--surface-1)' : 'transparent',
                    color: active ? t.color : 'var(--fg-2)',
                    fontFamily: 'var(--font-body)',
                    fontSize: 13,
                    fontWeight: active ? 700 : 500,
                    display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 6,
                    boxShadow: active ? 'var(--shadow-card)' : 'none',
                    transition: 'all 160ms var(--ease-out)',
                  }}
                >
                  <span className="material-icons" style={{ fontSize: 16 }}>{t.icon}</span>
                  {window.t(t.label)}
                </button>
              );
            })}
          </div>
        </div>

        {/* ── Step 2 · Input method ───────────────────────────── */}
        <div style={{ marginBottom: 22 }}>
          <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', marginBottom: 10 }}>
            <span style={{ fontFamily: 'var(--font-body)', fontSize: 11, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', color: 'var(--fg-3)' }}>
              {t('¿Cómo lo querés ingresar?')}
            </span>
            <span style={{ fontFamily: 'var(--font-body)', fontSize: 12, color: 'var(--fg-2)' }}>
              {t('Paso 2 de 2')}
            </span>
          </div>

          <div style={{
            display: 'grid',
            gridTemplateColumns: '1fr 1fr',
            gap: 10,
          }}>
            {DQM_METHODS.map(m => (
              <DQMMethodTile
                key={m.id}
                method={m}
                typeColor={activeType.color}
                onPress={() => choose(m.id)}
              />
            ))}
          </div>
        </div>

        {/* Separator */}
        <div style={{ height: 1, background: 'var(--border-hairline)', margin: '0 0 18px' }} />

        {/* ── Special plans · Deudas / Sueños / Jars ────────── */}
        <div style={{ marginBottom: 20 }}>
          <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', marginBottom: 10 }}>
            <span style={{ fontFamily: 'var(--font-body)', fontSize: 11, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', color: 'var(--fg-3)' }}>
              {t('O registrá un movimiento especial')}
            </span>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : 'repeat(3, 1fr)', gap: 10 }}>
            {DQM_PLANS.map(p => (
              <button
                key={p.id}
                onClick={() => choosePlan(p.id)}
                onMouseEnter={e => { e.currentTarget.style.borderColor = p.accent; e.currentTarget.style.background = p.tint; }}
                onMouseLeave={e => { e.currentTarget.style.borderColor = 'var(--border-hairline)'; e.currentTarget.style.background = 'var(--surface-1)'; }}
                style={{
                  textAlign: 'left', cursor: 'pointer',
                  border: '1px solid var(--border-hairline)',
                  background: 'var(--surface-1)',
                  borderRadius: 'var(--radius-lg)',
                  padding: '12px 12px 14px',
                  display: 'flex', flexDirection: 'column', gap: 6,
                  transition: 'all 160ms var(--ease-out)',
                  position: 'relative',
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                  <div style={{
                    width: 28, height: 28, borderRadius: 'var(--radius-sm)',
                    background: p.tint,
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                  }}>
                    <span className="material-icons" style={{ fontSize: 16, color: p.accent }}>{p.icon}</span>
                  </div>
                  <span style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 13, color: 'var(--fg-1)' }}>{t(p.label)}</span>
                  {p.badge && (
                    <span style={{
                      marginLeft: 'auto',
                      fontFamily: 'var(--font-body)', fontSize: 9, fontWeight: 700,
                      padding: '2px 6px', borderRadius: 'var(--radius-pill)',
                      background: p.tint, color: p.accent,
                      letterSpacing: '0.04em', textTransform: 'uppercase',
                    }}>
                      {t(p.badge)}
                    </span>
                  )}
                </div>
                <span style={{ fontFamily: 'var(--font-body)', fontSize: 11.5, color: 'var(--fg-2)', lineHeight: 1.4 }}>
                  {t(p.sub)}
                </span>
              </button>
            ))}
          </div>
        </div>

        {/* Separator */}
        <div style={{ height: 1, background: 'var(--border-hairline)', margin: '0 0 18px' }} />

        {/* AI Advisor CTA */}
        <button
          onClick={() => { onClose(); onOpenAI && onOpenAI(); }}
          style={{
            width: '100%', border: 0, cursor: 'pointer',
            display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 10,
            padding: '14px',
            borderRadius: 'var(--radius-pill)',
            background: 'linear-gradient(90deg, #7C3AED 0%, #2563EB 60%, #0EA5E9 100%)',
            color: '#fff',
            fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 15,
            boxShadow: '0 6px 24px rgba(124,58,237,0.30)',
            transition: 'opacity 160ms',
          }}
          onMouseEnter={e => e.currentTarget.style.opacity = '0.88'}
          onMouseLeave={e => e.currentTarget.style.opacity = '1'}
        >
          <span className="material-icons" style={{ fontSize: 20 }}>psychology</span>
          {t('¿Tenés una duda? Hablá con el Asesor IA')}
        </button>
      </div>
    </div>
  );
}

/* ─── Method tile ──────────────────────────────────────────────────── */
function DQMMethodTile({ method: m, typeColor, onPress }) {
  const [hover, setHover] = React.useState(false);
  return (
    <button
      onClick={onPress}
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
      style={{
        textAlign: 'left',
        border: '1px solid',
        borderColor: hover ? m.accent : 'var(--border-hairline)',
        cursor: 'pointer',
        background: hover ? m.tint : 'var(--surface-1)',
        borderRadius: 'var(--radius-lg)',
        padding: '14px 14px 16px',
        display: 'flex', flexDirection: 'column', gap: 8,
        transition: 'all 160ms var(--ease-out)',
        position: 'relative',
        minHeight: 116,
      }}
    >
      {/* Top row: icon + label + badge */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
        <div style={{
          width: 36, height: 36, borderRadius: 'var(--radius-md)',
          background: m.tint,
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          flexShrink: 0,
        }}>
          <span className="material-icons" style={{ fontSize: 20, color: m.accent }}>{m.icon}</span>
        </div>
        <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8 }}>
          <span style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 15, color: 'var(--fg-1)' }}>
            {t(m.label)}
          </span>
          {m.badge && (
            <span style={{
              fontFamily: 'var(--font-body)',
              fontSize: 10, fontWeight: 700, letterSpacing: '0.04em',
              padding: '3px 7px',
              borderRadius: 'var(--radius-pill)',
              background: m.tint, color: m.accent,
              textTransform: 'uppercase',
            }}>
              {t(m.badge)}
            </span>
          )}
        </div>
      </div>

      {/* Subline */}
      <span style={{ fontFamily: 'var(--font-body)', fontSize: 12.5, color: 'var(--fg-2)', lineHeight: 1.45 }}>
        {t(m.sub)}
      </span>

      {/* Detail chips (photo only) */}
      {m.chips && (
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginTop: 'auto', paddingTop: 4 }}>
          {m.chips.map(c => (
            <span key={c} style={{
              fontFamily: 'var(--font-body)',
              fontSize: 10.5, fontWeight: 600,
              padding: '3px 7px',
              borderRadius: 'var(--radius-pill)',
              background: 'var(--surface-2)',
              color: 'var(--fg-2)',
              border: '1px solid var(--border-hairline)',
            }}>
              {t(c)}
            </span>
          ))}
        </div>
      )}
    </button>
  );
}

Object.assign(window, { DesktopQuickModal });
