// src/components/SharedAccountsSection.vue
<template>
  <div class="sas">
    <!-- ── Mis cuentas ─────────────────────────────────────────────────── -->
    <div class="sas__card">
      <div class="sas__section-head">
        <span class="sas__eyebrow">Mis cuentas</span>
        <span class="sas__count">{{ myAccounts.length }}</span>
      </div>
      <div class="sas__list">
        <div v-for="(a, i) in myAccounts" :key="a.id" class="sas__row" :class="{ 'sas__row--first': i === 0 }">
          <q-avatar size="36px" color="grey-3" text-color="grey-8">{{ a.name.charAt(0).toUpperCase() }}</q-avatar>
          <div class="sas__row-text">
            <div class="sas__row-name">{{ a.name }}</div>
            <div class="sas__label">{{ a.currencyCode || 'USD' }}</div>
          </div>
          <div class="sas__amount">{{ formatMoney(a.balance || 0, a.currencySymbol || '$') }}</div>
          <button class="sas__icon-btn" title="Compartir con mi grupo familiar" @click="emit('share', a.id)">
            <q-icon name="group_add" size="20px" />
          </button>
        </div>
      </div>
    </div>

    <!-- ── Compartidas conmigo ─────────────────────────────────────────── -->
    <div class="sas__card">
      <div class="sas__section-head">
        <span class="sas__eyebrow">Compartidas conmigo</span>
        <span class="sas__count">{{ shares.length }}</span>
      </div>
      <div class="sas__list">
        <p v-if="!loading && shares.length === 0" class="sas__label sas__empty">
          Nadie de tu grupo familiar te compartió una cuenta todavía.
        </p>
        <div v-for="(s, i) in shares" :key="s.id" class="sas__shared-item" :class="{ 'sas__row--first': i === 0 }">
          <div class="sas__row" style="cursor: pointer;" @click="toggleOpen(s.id)">
            <q-avatar size="36px" color="grey-3" text-color="grey-8">{{ s.name.charAt(0).toUpperCase() }}</q-avatar>
            <div class="sas__row-text">
              <div class="sas__row-name">{{ s.name }}</div>
              <div class="sas__owner-line">
                <q-avatar size="16px" color="grey-3" text-color="grey-8">{{ (s.owner?.name || '?').charAt(0).toUpperCase() }}</q-avatar>
                <span class="sas__label">Compartida por {{ s.owner?.name || 'desconocido' }}</span>
              </div>
            </div>
            <div class="sas__shared-meta">
              <div class="sas__amount">{{ formatMoney(s.balance, s.currency?.symbol || '$') }}</div>
              <span class="sas__perm-badge" :style="permBadgeStyle(s.permission)">
                <q-icon :name="owfPermission(s.permission).icon" size="13px" />{{ owfPermission(s.permission).badge }}
              </span>
            </div>
          </div>

          <div v-if="openId === s.id" class="sas__detail">
            <div v-if="s.permission === 'view_balance'" class="sas__lock-box">
              <q-icon name="lock" size="20px" color="grey-5" />
              <div class="sas__lock-text">
                <div class="sas__lock-title">De esta cuenta ves solo el saldo</div>
                <p class="sas__label sas__lock-desc">
                  {{ s.owner?.name || 'El dueño' }} te compartió el saldo, no los movimientos. Si necesitás ver el
                  detalle, pedile que cambie el nivel de acceso.
                </p>
              </div>
            </div>
            <div v-else class="sas__tx-box">
              <div v-if="txLoading" class="sas__label" style="padding: 6px 0;">Cargando movimientos…</div>
              <template v-else-if="txByAccount[s.id]?.length">
                <div v-for="t in txByAccount[s.id]" :key="t.id" class="sas__tx-row">
                  <span class="sas__tx-name">{{ t.description || t.provider || 'Movimiento' }}</span>
                  <span class="sas__label">{{ t.date }}</span>
                  <span class="sas__tx-amount" :class="t.amount < 0 ? '' : 'sas__tx-amount--income'">
                    {{ t.amount < 0 ? '-' : '+' }}{{ formatMoney(Math.abs(t.amount), s.currency?.symbol || '$') }}
                  </span>
                </div>
              </template>
              <div v-else class="sas__label" style="padding: 6px 0;">Todavía no hay movimientos en esta cuenta.</div>
              <div class="sas__tx-footer">
                <p class="sas__label" style="flex: 1; margin: 0;">
                  {{ s.permission === 'manage' ? 'Podés registrar y editar movimientos en esta cuenta.' : 'Ves todo el detalle, sin poder editar.' }}
                </p>
                <q-btn v-if="s.permission === 'manage'" size="sm" unelevated rounded color="primary" icon="add" label="Registrar movimiento" @click="emit('register', s.id)" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { api } from 'boot/axios';
import { useFamilyGroupStore } from 'stores/familyGroup';
import { owfPermission, owfPermTint } from 'src/utils/familyPermissions';

defineOptions({ name: 'SharedAccountsSection' });

interface MyAccountLite {
  id: number;
  name: string;
  balance?: number;
  currencyCode?: string;
  currencySymbol?: string;
}

defineProps<{
  myAccounts: MyAccountLite[];
}>();

const emit = defineEmits<{
  (e: 'share', accountId: number): void;
  (e: 'register', accountId: number): void;
}>();

const store = useFamilyGroupStore();
const loading = ref(false);
const shares = computed(() => store.sharedWithMe);

const openId = ref<number | null>(null);
const txLoading = ref(false);
interface SharedTx { id: number; description?: string; provider?: string; date: string; amount: number }
const txByAccount = ref<Record<number, SharedTx[]>>({});

function formatMoney(v: number, symbol: string) {
  return `${symbol}${Number(v || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function permBadgeStyle(permission: string | null) {
  const p = owfPermission(permission);
  const tint = owfPermTint(p.weight, true);
  return { background: tint.background, color: tint.color };
}

async function toggleOpen(accountId: number) {
  if (openId.value === accountId) {
    openId.value = null;
    return;
  }
  openId.value = accountId;
  const share = store.sharedWithMe.find((s) => s.id === accountId);
  if (!share || share.permission === 'view_balance' || txByAccount.value[accountId]) return;

  txLoading.value = true;
  try {
    const res = await api.get('/transactions', { params: { payment_account_ids: String(accountId), per_page: 5 } });
    type RawTx = { id: number; description?: string; provider?: string; date?: string; created_at?: string; amount?: string | number };
    const dat = res.data?.data;
    const rawList: RawTx[] = Array.isArray(dat) ? dat : Array.isArray(dat?.data) ? dat.data : [];
    txByAccount.value = {
      ...txByAccount.value,
      [accountId]: rawList.map((t) => ({
        id: t.id,
        description: t.description ?? '',
        provider: t.provider ?? '',
        date: (t.date || t.created_at || '').slice(0, 10),
        amount: Number(t.amount || 0),
      })),
    };
  } catch {
    txByAccount.value = { ...txByAccount.value, [accountId]: [] };
  } finally {
    txLoading.value = false;
  }
}

async function reload() {
  loading.value = true;
  try {
    await store.fetchSharedWithMe();
  } finally {
    loading.value = false;
  }
}

void reload();
</script>

<style scoped>
.sas { display: flex; flex-direction: column; gap: 16px; max-width: 660px; }
.sas__card { background: var(--surface-1); border-radius: var(--radius-lg); box-shadow: var(--shadow-card); padding: 22px; }
.sas__section-head { display: flex; align-items: baseline; gap: 8px; margin-bottom: 6px; }
.sas__eyebrow { font-family: var(--font-display); font-size: 11px; font-weight: 700; letter-spacing: 0.09em; text-transform: uppercase; color: var(--fg-3); }
.sas__count { font-family: var(--font-money); font-size: 11px; color: var(--fg-3); }
.sas__list { display: flex; flex-direction: column; }
.sas__label { font-family: var(--font-body); font-size: 13px; color: var(--fg-2); }
.sas__empty { font-size: 12.5px; padding: 6px 0 2px; }

.sas__row { display: flex; align-items: center; gap: 14px; padding: 13px 0; border-top: 1px solid var(--border-hairline); }
.sas__row--first { border-top: none; }
.sas__row-text { flex: 1; min-width: 0; }
.sas__row-name { font-family: var(--font-body); font-weight: 600; font-size: 14.5px; color: var(--fg-1); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.sas__amount { font-family: var(--font-money); font-size: 14px; font-weight: 600; color: var(--fg-1); font-variant-numeric: tabular-nums; }
.sas__icon-btn { border: 0; background: transparent; cursor: pointer; color: var(--fg-3); display: flex; padding: 4px; }

.sas__owner-line { display: flex; align-items: center; gap: 6px; margin-top: 3px; }
.sas__shared-meta { display: flex; flex-direction: column; align-items: flex-end; gap: 5px; }
.sas__perm-badge {
  display: inline-flex; align-items: center; gap: 5px; font-family: var(--font-body); font-size: 11px; font-weight: 600;
  padding: 3px 9px; border-radius: var(--radius-pill);
}

.sas__detail { padding: 2px 0 16px; }
.sas__lock-box { display: flex; gap: 12px; padding: 16px; border-radius: var(--radius-lg); background: var(--surface-2); }
.sas__lock-text { min-width: 0; }
.sas__lock-title { font-family: var(--font-body); font-weight: 600; font-size: 13.5px; color: var(--fg-1); }
.sas__lock-desc { font-size: 12.5px; line-height: 1.5; margin-top: 5px; }

.sas__tx-box { padding: 16px; border-radius: var(--radius-lg); background: var(--surface-2); display: flex; flex-direction: column; gap: 10px; }
.sas__tx-row { display: flex; align-items: center; gap: 10px; }
.sas__tx-name { flex: 1; font-family: var(--font-body); font-size: 13.5px; color: var(--fg-1); }
.sas__tx-amount { font-family: var(--font-money); font-size: 13px; font-weight: 600; color: var(--fg-1); }
.sas__tx-amount--income { color: var(--income-fg); }
.sas__tx-footer { display: flex; align-items: center; gap: 10px; margin-top: 4px; }
</style>

// rediseno/ui_kits/lite-desktop/organisms/SharedAccountsSection.jsx
/* ─── Organism · SharedAccountsSection (Pro-only) ──────────────────────────
 * Pantalla 3 de la Fase 1: "Mis cuentas" vs "Compartidas conmigo", y el
 * límite real de `view_balance` al intentar abrir el detalle.
 *
 * Contrato de callbacks:
 *   onSelectAction('open:<account_id>' | 'share:<account_id>')
 *   onChange('selected', account_id | null)
 *
 * Regla visible: `view_balance` muestra el saldo pero no lista movimientos.
 * Eso NO es un error — es el permiso funcionando. Se explica en una línea.
 * ──────────────────────────────────────────────────────────────────────── */
/* global React, Avatar, Money, PillButton, owfPermission, owfPermTint */

function SharedAccountsSection({ myAccounts = [], shares = [], selectedId = null, onSelectAction, onChange }) {
  const [ui, setUi] = React.useState({ open: selectedId });
  const label = { fontFamily: 'var(--font-body)', fontSize: 13, color: 'var(--fg-2)' };
  const card = { background: 'var(--surface-1)', borderRadius: 'var(--radius-lg)', boxShadow: 'var(--shadow-card)', padding: 22 };

  const Section = ({ title, count, children }) => (
    <div style={card}>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 8, marginBottom: 6 }}>
        <span className="t-eyebrow" style={{ fontFamily: 'var(--font-display)', fontSize: 11, fontWeight: 700, letterSpacing: '0.09em', textTransform: 'uppercase', color: 'var(--fg-3)' }}>{title}</span>
        <span style={{ fontFamily: 'var(--font-money)', fontSize: 11, color: 'var(--fg-3)' }}>{count}</span>
      </div>
      <div style={{ display: 'flex', flexDirection: 'column' }}>{children}</div>
    </div>
  );

  const openShare = ui.open ? shares.find(s => s.account_id === ui.open) : null;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16, maxWidth: 660 }}>
      <Section title="Mis cuentas" count={myAccounts.length}>
        {myAccounts.map((a, i) => (
          <div key={a.id} style={{ display: 'flex', alignItems: 'center', gap: 14, padding: '13px 0', borderTop: i === 0 ? 'none' : '1px solid var(--border-hairline)' }}>
            <Avatar initial={a.name.charAt(0)} size={36} />
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{ fontFamily: 'var(--font-body)', fontWeight: 600, fontSize: 14.5, color: 'var(--fg-1)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{a.name}</div>
              <div style={{ ...label, fontSize: 12.5, marginTop: 2 }}>{a.currencyCode || 'USD'}</div>
            </div>
            <Money value={a.balance || 0} currency={a.currencySymbol || '$'} className="t-amount-sm" />
            <button onClick={() => onSelectAction && onSelectAction('share:' + a.id)} title="Compartir con mi grupo familiar" style={{ border: 0, background: 'transparent', cursor: 'pointer', color: 'var(--fg-3)', display: 'flex', padding: 4 }}>
              <span className="material-icons" style={{ fontSize: 20 }}>group_add</span>
            </button>
          </div>
        ))}
      </Section>

      <Section title="Compartidas conmigo" count={shares.length}>
        {shares.length === 0 && (
          <p style={{ ...label, fontSize: 12.5, padding: '6px 0 2px' }}>Nadie de tu grupo familiar te compartió una cuenta todavía.</p>
        )}
        {shares.map((s, i) => {
          const perm = owfPermission(s.permission);
          const tint = owfPermTint(perm.weight, true);
          return (
            <div key={s.account_id} style={{ borderTop: i === 0 ? 'none' : '1px solid var(--border-hairline)' }}>
              <div onClick={() => { setUi({ open: ui.open === s.account_id ? null : s.account_id }); onChange && onChange('selected', ui.open === s.account_id ? null : s.account_id); }}
                style={{ display: 'flex', alignItems: 'center', gap: 14, padding: '13px 0', cursor: 'pointer' }}>
                <Avatar initial={s.account_name.charAt(0)} size={36} />
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ fontFamily: 'var(--font-body)', fontWeight: 600, fontSize: 14.5, color: 'var(--fg-1)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{s.account_name}</div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginTop: 3 }}>
                    <Avatar initial={s.owner_name.charAt(0)} size={16} />
                    <span style={{ ...label, fontSize: 12.5 }}>Compartida por {s.owner_name}</span>
                  </div>
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 5 }}>
                  <Money value={s.balance} currency={s.currency_symbol} className="t-amount-sm" />
                  <span style={{ display: 'inline-flex', alignItems: 'center', gap: 5, fontFamily: 'var(--font-body)', fontSize: 11, fontWeight: 600, padding: '3px 9px', borderRadius: 'var(--radius-pill)', background: tint.background, color: tint.color }}>
                    <span className="material-icons" style={{ fontSize: 13 }}>{perm.icon}</span>{perm.badge}
                  </span>
                </div>
              </div>

              {ui.open === s.account_id && (
                <div style={{ padding: '2px 0 16px' }}>
                  {s.permission === 'view_balance' ? (
                    <div style={{ display: 'flex', gap: 12, padding: 16, borderRadius: 'var(--radius-lg)', background: 'var(--surface-2)' }}>
                      <span className="material-icons" style={{ fontSize: 20, color: 'var(--fg-3)' }}>lock</span>
                      <div style={{ minWidth: 0 }}>
                        <div style={{ fontFamily: 'var(--font-body)', fontWeight: 600, fontSize: 13.5, color: 'var(--fg-1)' }}>De esta cuenta ves solo el saldo</div>
                        <p style={{ ...label, fontSize: 12.5, lineHeight: 1.5, marginTop: 5, textWrap: 'pretty' }}>
                          {s.owner_name} te compartió el saldo, no los movimientos. Si necesitás ver el detalle, pedile que cambie el nivel de acceso.
                        </p>
                      </div>
                    </div>
                  ) : (
                    <div style={{ padding: 16, borderRadius: 'var(--radius-lg)', background: 'var(--surface-2)', display: 'flex', flexDirection: 'column', gap: 10 }}>
                      {[['Supermercado', -42.3, '18 ago'], ['Pago recibido', 180, '15 ago'], ['Farmacia', -12.9, '14 ago']].map(([n, v, d]) => (
                        <div key={n} style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                          <span style={{ flex: 1, fontFamily: 'var(--font-body)', fontSize: 13.5, color: 'var(--fg-1)' }}>{n}</span>
                          <span style={{ ...label, fontSize: 12 }}>{d}</span>
                          <Money value={v} currency={s.currency_symbol} className="t-amount-sm" sign color={v < 0 ? 'var(--fg-1)' : 'var(--income-fg)'} />
                        </div>
                      ))}
                      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginTop: 4 }}>
                        <p style={{ ...label, fontSize: 12.5, flex: 1 }}>
                          {s.permission === 'manage' ? 'Podés registrar y editar movimientos en esta cuenta.' : 'Ves todo el detalle, sin poder editar.'}
                        </p>
                        {s.permission === 'manage' && <PillButton size="sm" icon="add" onClick={() => onSelectAction && onSelectAction('open:' + s.account_id)}>Registrar movimiento</PillButton>}
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          );
        })}
      </Section>
    </div>
  );
}

Object.assign(window, { SharedAccountsSection });
