// rediseno/ui_kits/lite-desktop/organisms/BusinessEmptyState.jsx
/* ─── Organism · BusinessEmptyState (Fase 2) ──────────────────────────────
 * La primera pantalla real de una empresa recién creada. No es un "no hay
 * datos": es el arranque, y por eso no dice qué falta sino qué sigue.
 *
 * Por qué no muestra un Inicio de ceros: una pantalla con "$ 0.00", cántaros
 * al 0% y una lista vacía se lee como un error del sistema, no como una cuenta
 * nueva. Con cero movimientos no hay nada que resumir.
 *
 * Tres pasos, en el orden en que se pueden hacer de verdad:
 *   1. El onboarding de la empresa (D-011) — es el que deja cántaros y
 *      categorías listas, así que va primero y destacado.
 *   2. Una cuenta — sin cuenta no se puede registrar nada.
 *   3. El primer movimiento — queda deshabilitado hasta que haya una cuenta,
 *      con el motivo escrito. Un botón que falla al tocarlo es peor que uno
 *      apagado que dice por qué.
 *
 * Props: ctx(object) · hasAccounts(bool) · onboarded(bool)
 *        onOnboard · onAddAccount · onAddTx
 * ──────────────────────────────────────────────────────────────────────── */
/* global React */

function BusinessEmptyState({ ctx = {}, hasAccounts = false, onboarded = false, onOnboard, onAddAccount, onAddTx }) {
  const tint = ctx.color || 'var(--brand-primary)';
  const steps = [
    {
      n: 1, icon: 'auto_awesome', primary: !onboarded,
      title: 'Configurá la empresa',
      body: onboarded
        ? 'Listo. Los cántaros quedaron armados con el reparto que elegiste.'
        : 'Unas preguntas sobre el negocio — rubro, facturación esperada, temporadas — y quedan los cántaros armados.',
      cta: 'Empezar', action: onOnboard, minutes: onboarded ? null : '3 minutos',
      done: onboarded,
    },
    {
      n: 2, icon: 'account_balance', primary: onboarded,
      title: 'Agregá una cuenta',
      body: 'El banco, la caja o lo que use la empresa para cobrar y pagar.',
      cta: 'Agregar cuenta', action: onAddAccount,
      done: hasAccounts,
    },
    {
      n: 3, icon: 'receipt_long',
      title: 'Registrá el primer movimiento',
      body: hasAccounts ? 'Un cobro o un gasto de la empresa.' : 'Necesita una cuenta primero: un movimiento tiene que entrar o salir de algún lado.',
      cta: 'Registrar', action: onAddTx, disabled: !hasAccounts,
    },
  ];

  return (
    <div style={{ padding: '28px 22px 44px', display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
      <div style={{ width: '100%', maxWidth: 640, display: 'flex', flexDirection: 'column', gap: 22 }}>

        <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
          <span style={{ width: 46, height: 46, borderRadius: 13, flexShrink: 0, background: tint, color: '#fff', display: 'grid', placeItems: 'center', fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 19 }}>
            {(ctx.name || 'E').charAt(0).toUpperCase()}
          </span>
          <div style={{ minWidth: 0 }}>
            <h2 style={{ margin: 0, fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 21, color: 'var(--fg-1)', letterSpacing: '-.2px' }}>{ctx.name || 'Tu empresa'}</h2>
            <p style={{ margin: '3px 0 0', fontFamily: 'var(--font-body)', fontSize: 13.5, lineHeight: 1.5, color: 'var(--fg-2)', textWrap: 'pretty' }}>
              Está creada y vacía. Sus cuentas, cántaros y movimientos son aparte de los tuyos.
            </p>
          </div>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 11 }}>
          {steps.map(s => (
            <div key={s.n} style={{ display: 'flex', alignItems: 'flex-start', gap: 14, padding: '17px 18px', borderRadius: 'var(--radius-lg)', background: 'var(--surface-1)', border: `1px solid ${s.primary ? tint : 'var(--border-hairline)'}`, boxShadow: s.primary ? 'var(--shadow-card)' : 'none', opacity: s.disabled ? .72 : 1 }}>
              <span style={{ width: 34, height: 34, borderRadius: 10, flexShrink: 0, display: 'grid', placeItems: 'center', background: s.done ? 'var(--income-soft)' : s.primary ? tint : 'var(--surface-2)', color: s.done ? 'var(--income-fg)' : s.primary ? '#fff' : 'var(--fg-2)' }}>
                <span className="material-icons" style={{ fontSize: 18 }}>{s.done ? 'check' : s.icon}</span>
              </span>
              <div style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', gap: 3 }}>
                <div style={{ display: 'flex', alignItems: 'baseline', gap: 8, flexWrap: 'wrap' }}>
                  <span style={{ fontFamily: 'var(--font-display)', fontWeight: 600, fontSize: 15, color: 'var(--fg-1)' }}>{s.title}</span>
                  {s.minutes && <span style={{ fontFamily: 'var(--font-body)', fontSize: 11.5, color: 'var(--fg-3)' }}>{s.minutes}</span>}
                </div>
                <p style={{ margin: 0, fontFamily: 'var(--font-body)', fontSize: 13, lineHeight: 1.5, color: 'var(--fg-2)', textWrap: 'pretty' }}>{s.body}</p>
              </div>
              {!s.done && (
                <button type="button" onClick={s.disabled ? undefined : s.action} disabled={s.disabled}
                  style={{ flexShrink: 0, border: s.primary ? 0 : '1px solid var(--border-hairline)', cursor: s.disabled ? 'default' : 'pointer', padding: '10px 18px', borderRadius: 'var(--radius-pill)', background: s.primary ? tint : 'transparent', color: s.primary ? '#fff' : 'var(--fg-1)', fontFamily: 'var(--font-body)', fontWeight: 600, fontSize: 13, whiteSpace: 'nowrap' }}>
                  {s.cta}
                </button>
              )}
            </div>
          ))}
        </div>

        {/* Lo que la app todavía no hace, dicho acá y no descubierto después
          * (D-011: nómina es Fase 4). */}
        <div style={{ display: 'flex', gap: 10, padding: '14px 16px', borderRadius: 'var(--radius-md)', background: 'var(--surface-2)' }}>
          <span className="material-icons" style={{ fontSize: 18, color: 'var(--fg-3)', flexShrink: 0 }}>schedule</span>
          <p style={{ margin: 0, fontFamily: 'var(--font-body)', fontSize: 12.5, lineHeight: 1.55, color: 'var(--fg-2)', textWrap: 'pretty' }}>
            La gestión de empleados y pagos de nómina llega más adelante. Por ahora la empresa lleva cuentas, cántaros y movimientos.
          </p>
        </div>
      </div>
    </div>
  );
}

Object.assign(window, { BusinessEmptyState });

// src/components/business/BusinessEmptyState.vue
<template>
  <div v-if="visible" class="bes">
    <div class="bes__inner">
      <div class="bes__head">
        <span class="bes__mark" :style="{ background: tint }">{{ (business?.name ?? 'E').charAt(0).toUpperCase() }}</span>
        <div class="bes__head-text">
          <h2 class="bes__name">{{ business?.name ?? 'Tu empresa' }}</h2>
          <p class="bes__desc">Está creada y casi vacía. Sus cuentas y movimientos son aparte de los tuyos.</p>
        </div>
      </div>

      <div class="bes__steps">
        <div v-for="s in steps" :key="s.n" class="bes__step" :style="s.primary ? { borderColor: tint } : undefined">
          <span class="bes__icon" :class="{ 'bes__icon--done': s.done }" :style="s.primary && !s.done ? { background: tint, color: '#fff' } : undefined">
            <q-icon :name="s.done ? 'check' : s.icon" size="18px" />
          </span>
          <div class="bes__step-text">
            <div class="bes__step-title">
              {{ s.title }} <span v-if="s.minutes" class="bes__minutes">{{ s.minutes }}</span>
            </div>
            <p class="bes__step-body">{{ s.body }}</p>
          </div>
          <q-btn
            v-if="!s.done && s.show"
            :unelevated="s.primary"
            :outline="!s.primary"
            rounded
            no-caps
            size="md"
            :label="s.cta"
            :disable="s.disabled"
            :style="s.primary ? { background: tint, color: '#fff' } : undefined"
            @click="s.action"
          />
        </div>
      </div>

      <div class="bes__note">
        <q-icon name="schedule" size="18px" />
        <p>La gestión de empleados y pagos de nómina llega más adelante. Por ahora la empresa lleva cuentas, cántaros y movimientos.</p>
      </div>
    </div>

    <BusinessOnboardingFlow v-model="showOnboarding" :business="business" @done="onOnboarded" />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { api } from 'boot/axios';
import { useBusinessStore } from 'stores/business';
import { useUiStore } from 'stores/ui';
import BusinessOnboardingFlow from './BusinessOnboardingFlow.vue';

defineOptions({ name: 'BusinessEmptyState' });

/**
 * Arranque de una empresa recién creada. Se auto-oculta: solo se ve en contexto
 * de empresa y mientras falte configurarla o crear la primera cuenta.
 * (Las cuentas se piden con el contexto activo: el interceptor añade business_id.)
 */
const router = useRouter();
const store = useBusinessStore();
const ui = useUiStore();

const business = computed(() => store.activeBusiness);
const tint = computed(() => business.value?.color ?? 'var(--brand-primary)');
const onboarded = computed(() => !!business.value?.onboarded_at);
const isOwner = computed(() => store.isOwner);
const hasAccounts = ref<boolean | null>(null);
const showOnboarding = ref(false);

async function loadAccountsCount() {
  if (!business.value) {
    hasAccounts.value = null;
    return;
  }
  try {
    const res = await api.get('/accounts', { params: { per_page: 1 } });
    const raw = res.data?.data;
    const list = Array.isArray(raw) ? raw : Array.isArray(raw?.data) ? (raw.data as unknown[]) : [];
    hasAccounts.value = list.length > 0;
  } catch {
    hasAccounts.value = null;
  }
}

onMounted(() => void loadAccountsCount());
watch(() => business.value?.id, () => void loadAccountsCount());

// Visible mientras falte algo; un viewer no puede completar nada, así que no se le muestra el arranque.
const visible = computed(
  () => !!business.value && hasAccounts.value !== null && (!onboarded.value || !hasAccounts.value) && store.canWrite,
);

const steps = computed(() => [
  {
    n: 1, icon: 'auto_awesome', primary: !onboarded.value, done: onboarded.value,
    title: 'Configurá la empresa',
    body: onboarded.value
      ? 'Listo. La empresa quedó configurada con tus respuestas.'
      : 'Unas preguntas sobre el negocio — rubro, facturación esperada, temporadas.',
    cta: 'Empezar', minutes: onboarded.value ? null : '3 minutos', disabled: false,
    show: isOwner.value, action: () => { showOnboarding.value = true; },
  },
  {
    n: 2, icon: 'account_balance', primary: onboarded.value && !hasAccounts.value, done: !!hasAccounts.value,
    title: 'Agregá una cuenta',
    body: 'El banco, la caja o lo que use la empresa para cobrar y pagar.',
    cta: 'Agregar cuenta', minutes: null, disabled: false,
    show: isOwner.value, action: () => { void router.push('/user/config'); },
  },
  {
    n: 3, icon: 'receipt_long', primary: false, done: false,
    title: 'Registrá el primer movimiento',
    body: hasAccounts.value
      ? 'Un cobro o un gasto de la empresa.'
      : 'Necesita una cuenta primero: un movimiento tiene que entrar o salir de algún lado.',
    cta: 'Registrar', minutes: null, disabled: !hasAccounts.value,
    show: true, action: () => { ui.openSmartModal(); },
  },
]);

function onOnboarded() {
  // la lista ya se actualizó en la store (upsertLocal); refrescar conteo de cuentas por si cambió
  void loadAccountsCount();
}
</script>

<style scoped lang="scss">
.bes {
  padding: 28px 22px 12px;
  display: flex;
  flex-direction: column;
  align-items: center;

  &__inner { width: 100%; max-width: 640px; display: flex; flex-direction: column; gap: 22px; }
  &__head { display: flex; align-items: center; gap: 14px; }
  &__mark {
    width: 46px; height: 46px; border-radius: 13px; flex-shrink: 0; color: #fff;
    display: grid; place-items: center; font-weight: 700; font-size: 19px;
  }
  &__head-text { min-width: 0; }
  &__name { margin: 0; font-family: var(--font-display); font-weight: 700; font-size: 21px; color: var(--fg-1); }
  &__desc { margin: 3px 0 0; font-size: 13.5px; line-height: 1.5; color: var(--fg-2); }
  &__steps { display: flex; flex-direction: column; gap: 11px; }
  &__step {
    display: flex; align-items: flex-start; gap: 14px; padding: 17px 18px; border-radius: var(--radius-lg, 16px);
    background: var(--surface-1); border: 1px solid var(--border-hairline);
  }
  &__icon {
    width: 34px; height: 34px; border-radius: 10px; flex-shrink: 0; display: grid; place-items: center;
    background: var(--surface-2); color: var(--fg-2);
    &--done { background: var(--income-soft, #dcfce7); color: var(--income-fg, #15803d); }
  }
  &__step-text { flex: 1; min-width: 0; display: flex; flex-direction: column; gap: 3px; }
  &__step-title { font-family: var(--font-display); font-weight: 600; font-size: 15px; color: var(--fg-1); }
  &__minutes { font-family: var(--font-body); font-weight: 400; font-size: 11.5px; color: var(--fg-3); margin-left: 6px; }
  &__step-body { margin: 0; font-size: 13px; line-height: 1.5; color: var(--fg-2); }
  &__note {
    display: flex; gap: 10px; padding: 14px 16px; border-radius: 12px; background: var(--surface-2); color: var(--fg-2);
    p { margin: 0; font-size: 12.5px; line-height: 1.55; }
  }
}
</style>
